plugins {
    id 'com.android.application'
}

def releaseKeystorePath = System.getenv("ANDROID_KEYSTORE_PATH")
def releaseKeystorePassword = System.getenv("ANDROID_KEYSTORE_PASSWORD")
def releaseKeyAlias = System.getenv("ANDROID_KEY_ALIAS")
def releaseKeyPassword = System.getenv("ANDROID_KEY_PASSWORD")

android {
    namespace 'br.com.controlesolar.residencia'
    compileSdk 35

    defaultConfig {
        applicationId "br.com.controlesolar.residencia"
        minSdk 24
        targetSdk 35
        versionCode 11
        versionName "2.8.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            if (releaseKeystorePath && releaseKeystorePassword && releaseKeyAlias && releaseKeyPassword) {
                storeFile file(releaseKeystorePath)
                storePassword releaseKeystorePassword
                keyAlias releaseKeyAlias
                keyPassword releaseKeyPassword
            }
        }
    }

    buildTypes {
        debug {
            applicationIdSuffix ""
            versionNameSuffix ""
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
}

dependencies {
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test:rules:1.6.1'
    androidTestImplementation 'junit:junit:4.13.2'
}
