plugins {
    id 'com.android.application'
}

android {
    namespace 'br.com.controlesolar.residencia'
    compileSdk 35

    defaultConfig {
        applicationId "br.com.controlesolar.residencia"
        minSdk 24
        targetSdk 35
        versionCode 2
        versionName "2.0"
    }

    buildTypes {
        debug {
            applicationIdSuffix ""
            versionNameSuffix ""
        }
        release {
            minifyEnabled false
        }
    }
}
